### ISSUE TITLE
Imagte picker with bytes randomly does nothing on iOS web browser (Chrome or Safari)

### ISSUE THREAD

**Issue by davidlepilote** [TesteurManiak/image_picker_web_redux#1]

**Comment by davidlepilote** [comment]
After some research, it seems that the InputElement must be added to the DOM so iOS web want to use it

`html.document.body.append(uploadInput);`

If you do this before subscribing to onChange, it seems to do the trick

**Comment by TesteurManiak** [comment]
You are right, the line was added for the `pickMultiFiles` but not for `pickFile`. I am adding it !

**Comment by TesteurManiak** [comment]
I've merged the fix for `1.1.2` and I am closing this issue, do not hesitate to reopen it if you still encounter this problem.
