### ISSUE TITLE
[Suggestions]: Null-Safety + Package Name

### ISSUE THREAD

**Issue by Ahmadre** [TesteurManiak/image_picker_web_redux#6]
Hello :)

Nice to see that someone is motivated to continue this (as long as Flutter isn't ready for the web implementation). Awesome work 👏🏻

One suggestion: It's easy to migrate to null-safety so actual Flutter builds are supported. Just do `dart migrate --apply-changes`

And one question: why is the project and package postfixed with "_redux"? I don't see any state management implementation of redux in here.

Keep up the awesome work :)

Best regards

PS: if you like I can add you as a maintainer and pub-admin so you can work with all rights on the main project 👍🏼

**Comment by TesteurManiak** [comment]
Hi !

Thanks a lot for the praise. Yes it is a great suggestion to migrate to nullsafety I will definitely do it.

The prefix "_redux" was suggested by a friend of mine as it is a term we use often to mean "remastered" or "remake" but I understand that it might confuse people with the state manager. (Didn't know it at the time I've released it ^^')

Wow, it would be great to be able to work on the original project so as many users who were previously using it would beneficiate from it.

**Comment by TesteurManiak** [comment]
Made the migration to nullsafety on my repo in #7 and accepted your invitation to maintain the original project. I don't know if I need any other permissions to be able to merge an update and publish it on pub.dev. (Once it will be merged in your repo I'll archive this repository and unlist my package from pub.dev)

**Comment by Ahmadre** [comment]
> Made the migration to nullsafety on my repo in #7 and accepted your invitation to maintain the original project. I don't know if I need any other permissions to be able to merge an update and publish it on pub.dev. (Once it will be merged in your repo I'll archive this repository and unlist my package from pub.dev)

Are you a verified publisher on pub.dev ? Because I encountered, that I can't add you as an uploader to pub.dev, when a package has the verified publisher tag....

**Comment by TesteurManiak** [comment]
Great, I've accepted it !

**Comment by TesteurManiak** [comment]
And its done, I've merged my package and published it on pub.dev, also have marked as discontinued the other one on pub.dev !
